steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_SOCKET_URL=https://chat-middleware-u25qpvjxya-uc.a.run.app
      - -t
      - gcr.io/$PROJECT_ID/chat-frontend:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/chat-frontend:latest']

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - chat-frontend
      - --image
      - gcr.io/$PROJECT_ID/chat-frontend:latest
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/chat-frontend:latest
